//  Generated by configure.bat
 
#ifndef __PLATFORM_H_INCLUDED__
#define __PLATFORM_H_INCLUDED__
 
#define CZMQ_HAVE_WINDOWS 
#define HAVE_LIBZMQ 
#define HAVE_UUID 
#define HAVE_SYSTEMD 
#define HAVE_LZ4 
#undef HAVE_LIBCURL
//  Provide draft classes and methods
#define CZMQ_BUILD_DRAFT_API 
 
#endif
